### ISSUE TITLE
FileExists implementation

### ISSUE THREAD

**Issue by LauJohansson** [spetlr-org/spetlr#70]
# Introduction 
PR #9 "Feature/streaming" needs a implementation of *FileExists* using dbutils.

I want to implement a solution like the following:

```python
from spetlr.functions import init_dbutils


def file_exists(path: str) -> bool:
    """
    Helper function to check whether a file or folder exists.
    """

    try:
        init_dbutils().fs.ls(path)
        return True
    except Exception as e:
        if "java.io.FileNotFoundException" in str(e):
            return False
        else:
            raise e
```

The function should be able to return `true` if the path can be found by dbutils, and `false` if the file or path does not exists.

# Issue
If you run this function in a notebook like `file_exists("some-invalid-path)` - the function works as it should.

BUT - when applying the function in the SPETLR pipeline and running the tests the following error is raised (and NOT catched by the try-except):

```
Traceback (most recent call last):
  File "/databricks/spark/python/pyspark/sql/utils.py", line 117, in deco
    return f(*a, **kw)
  File "/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.databricks.backend.daemon.dbutils.FSUtils.ls.
: java.io.FileNotFoundException: Operation failed: "The specified path does not exist.", 404, GET, 
https://dbstoragetw4cfm7efogae.dfs.core.windows.net/root?upn=false&resource=filesystem&maxResults=5000&directory=3720449084827368/tmp/c920fbb514b148a2a52ed0aa2b488474&timeout=90&recursive=false&sig=e7k6FWLA%2BDnooihFMHR9aS9B8%2F8bjdZknkR%2FC8RyxQQ%3D&st=2023-06-27T09%3A26%3A02Z&se=2023-06-28T05%3A26%3A02Z&sv=2019-02-02&spr=https&sp=racwdl&sr=c, PathNotFound, "The specified path does not exist. RequestId:c2b8a09d-d01f-005d-78df-a84b9d000000 Time:2023-06-27T10:06:15.6795720Z"

```

See: https://github.com/spetlr-org/spetlr/actions/runs/5387871530/jobs/9779780692

The pipeline error is a `py4j.protocol.Py4JJavaError`, but running the *file_exists* in a notebook you will get an `ExecutionError`.

Nevertheless, the *file_exists* should work for both due to this
 ```python
 if "java.io.FileNotFoundException" in str(e):
```

Both errors have *java.io.FileNotFoundException* in the errormessage. 

# Question

Can anybody assist on implementing a function that works as expected?

**Comment by RadekBuczkowski** [comment]
I betragtning af at tjekken er på Databricks serveren, giver det mening at bruge dbutils. "os" eller en hvilken som helst anden normal python-logik tjekker lokale filer, og det er ikke hensigten. Hvis du ikke kan fange "java.io.FileNotFoundException" direkt, skal du fange en mere generisk exception og søge efter "java.io.FileNotFoundException" i exception-teksten. IMHO. :)
